#!/bin/sh -

[ $1 ] && RES=$1 || RES=720;
[ ! -z "${RES##[0-9]*}" ] && RES=720;

[ $RES -eq 720 ] && moonlight stream -720 -30fps -mapping /home/pi/moonlight/ps3.map -app Steam;

[ $RES -eq 1080 ] && moonlight stream -1080 -30fps -mapping /home/pi/moonlight/ps3.map -app Steam;
