#!/bin/bash -

BIN=$(which moonlight)
if [ -z $BIN ];then echo "moonlight binary not found!"; exit; fi

[[ $1 ]] && RES=$1 || RES=1080;
[[ $2 ]] && FPS=$2 || FPS=60

[[ ! -z "${RES##[0-9]*}" ]] && RES=1080;
[[ ! -z "${FPS##[0-9]*}" ]] && FPS=60;

OPTS="-packetsize 1024 -bitrate 10000 -fps ${FPS} -unsupported -remote -nosops -app Steam -audio hw:0,0"

$BIN stream -${RES} -fps ${FPS} ${OPTS}
